-- MySQL Script generated by MySQL Workbench
-- Fri Jun 14 13:06:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LettleLemonDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LettleLemonDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LettleLemonDB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `LettleLemonDB` ;

-- -----------------------------------------------------
-- Table `LettleLemonDB`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LettleLemonDB`.`customer` (
  `Name` INT NOT NULL,
  `Phone number` VARCHAR(45) NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  `Customer ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Customer ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LettleLemonDB`.`deliver status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LettleLemonDB`.`deliver status` (
  `Delivery ID` INT NOT NULL,
  `Delivery Date` VARCHAR(45) NOT NULL,
  `Delivery Status` VARCHAR(45) NOT NULL,
  `Order ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Delivery ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LettleLemonDB`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LettleLemonDB`.`menu` (
  `Cuisines` INT NOT NULL,
  `Starters` VARCHAR(45) NOT NULL,
  `Courses` VARCHAR(45) NOT NULL,
  `Drinks` VARCHAR(45) NOT NULL,
  `Desserts` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cuisines`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LettleLemonDB`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LettleLemonDB`.`orders` (
  `Order Date` INT NOT NULL,
  `Quantity` VARCHAR(45) NOT NULL,
  `Total Cost` VARCHAR(45) NOT NULL,
  `deliver status_Delivery ID` INT NOT NULL,
  `menu_Cuisines` INT NOT NULL,
  PRIMARY KEY (`Order Date`),
  INDEX `fk_orders_deliver status1_idx` (`deliver status_Delivery ID` ASC) VISIBLE,
  INDEX `fk_orders_menu1_idx` (`menu_Cuisines` ASC) VISIBLE,
  CONSTRAINT `fk_orders_deliver status1`
    FOREIGN KEY (`deliver status_Delivery ID`)
    REFERENCES `LettleLemonDB`.`deliver status` (`Delivery ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_menu1`
    FOREIGN KEY (`menu_Cuisines`)
    REFERENCES `LettleLemonDB`.`menu` (`Cuisines`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LettleLemonDB`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LettleLemonDB`.`bookings` (
  `Booking ID` INT NOT NULL,
  `Date` VARCHAR(45) NOT NULL,
  `Table Number` VARCHAR(45) NOT NULL,
  `customer_Customer ID` VARCHAR(45) NOT NULL,
  `orders_Order Date` INT NOT NULL,
  PRIMARY KEY (`Booking ID`),
  INDEX `fk_bookings_customer_idx` (`customer_Customer ID` ASC) VISIBLE,
  INDEX `fk_bookings_orders1_idx` (`orders_Order Date` ASC) VISIBLE,
  CONSTRAINT `fk_bookings_customer`
    FOREIGN KEY (`customer_Customer ID`)
    REFERENCES `LettleLemonDB`.`customer` (`Customer ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_orders1`
    FOREIGN KEY (`orders_Order Date`)
    REFERENCES `LettleLemonDB`.`orders` (`Order Date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LettleLemonDB`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LettleLemonDB`.`staff` (
  `Name` INT NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Salary` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
